### ISSUE TITLE
Deprecate sync client

### ISSUE THREAD

**Issue by nhannamsiu** [InjectiveLabs/sdk-python#101]
### Motive
_Note: by the day this issue is filed, both clients have identical feature set._

With all the new features added lately to help reducing the chance to have sequence mismatch error, the logic flows in `sync` and `async` clients start to diverge. This will require more time and effort down the road to keep both clients, their examples and API doc up-to-date.

Given that `sync` client is a subset and way slower than `async` client, Injective MM & API users rarely apply it in their applications. I assume this deprecation would not introduce much trouble to the users while allowing us to focus on polishing async client and its examples, API documentation.

What do you guys think?

**Comment by achilleas-kal** [comment]
I fully agree, we can use the time we'd devote to the `sync` client to support the new SDKs in GO/Typescript and improve them. 

Market makers and API traders should use the async client since it's much faster and given how the nature of trading requires one to invoke multiple methods at a given time the `async client` is naturally the ideal choice since they can run concurrent coroutines.

Let's keep the `sync` client for the near-term (6-month period) but put a notice that it will no longer be supported - this should give ample time for anyone who might be using it to change to the `async client`.

**Comment by stokhos** [comment]
I agree. But I suggest that we just keep the sync client in the repo for some time before we fully remove it. Cause maybe people are still using it.

**Comment by DrunkRandomWalker** [comment]
Agreed.
